# Dependencies
markdown:         Kramdown
highlighter:         true
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - bower.json

layouts: ./_layouts

# Permalinks
permalink:        pretty

# Setup
title:            Byron Samaripa
tagline:          From Boulder With Love
url:              http://bsamaripa.github.io
paginate:         1
baseurl:          /
author:
  name:           Byron Samaripa
  url:            http://www.bsamaripa.com/
  email:          byron.samaripa@gmail.com
  twitter:        byronsamaripa
  facebook:       byronsamaripa
  linkedin:    pub/byron-samaripa/b/7b5/29b/
  github:         bsamaripa

# Custom vars
version:          0.1.0
github:
  repo:           https://github.com/bsamaripa/bsamaripa.github.io
